apiVersion: v1
kind: Pod
metadata:
  name: backend-db-pod
  labels:
    app: backend-db
spec:
  volumes:
    - name: postgres-storage
      emptyDir: {}
  containers:
    - name: db
      image: postgres
      ports:
        - containerPort: 5432
      env:
        - name: POSTGRES_USER
          value: odc
        - name: POSTGRES_PASSWORD
          value: odc123
        - name: POSTGRES_DB
          value: odcdb
      volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data

    - name: backend
      image: dakyh/filrouge-backend:latest
      ports:
        - containerPort: 8000
      env:
        - name: DB_NAME
          value: odcdb
        - name: DB_USER
          value: odc
        - name: DB_PASSWORD
          value: odc123
        - name: DB_HOST
          value: localhost
        - name: DB_PORT
          value: "5432"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend-db
  ports:
    - port: 8000
      targetPort: 8000
  type: ClusterIP
