apiVersion: v1
kind: Pod
metadata:
  name: frontend-pod
  labels:
    app: frontend
spec:
  containers:
    - name: frontend
      image: dakyh/filrouge-frontend:latest
      ports:
        - containerPort: 80
      env:
        - name: VITE_API_URL
          value: http://backend-service:8000  # communication backend depuis le cluster
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - port: 8081
      targetPort: 80
  type: LoadBalancer
